name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from release tag
        id: version
        run: |
          # Extract version from release tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update plugin version
        run: |
          PLUGIN_FILE="cf7-propstack-integration.php"

          # Update version in plugin file
          sed -i "s/Version: [0-9]\+\.[0-9]\+\.[0-9]\+/Version: ${{ steps.version.outputs.version }}/" "$PLUGIN_FILE"

          # Verify version was updated
          if ! grep -q "Version: ${{ steps.version.outputs.version }}" "$PLUGIN_FILE"; then
            echo "Error: Failed to update version in plugin file"
            exit 1
          fi

          echo "Version updated to ${{ steps.version.outputs.version }}"

      - name: Commit and push version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cf7-propstack-integration.php
          git commit -m "Bump version to ${{ steps.version.outputs.version }} [skip ci]"
          git push origin HEAD:main

      - name: Create plugin zip
        run: |
          # Create a temporary directory for the plugin
          mkdir -p temp/cf7-propstack-integration

          # Copy plugin files (excluding development files)
          cp -r * temp/cf7-propstack-integration/

          # Remove development files
          rm -rf temp/cf7-propstack-integration/.git
          rm -rf temp/cf7-propstack-integration/.github
          rm -f temp/cf7-propstack-integration/README.md
          rm -f temp/cf7-propstack-integration/.gitignore
          rm -f temp/cf7-propstack-integration/UPDATE.md

          # Create zip file
          cd temp
          zip -r cf7-propstack-integration.zip cf7-propstack-integration/

          # Move zip to root
          mv cf7-propstack-integration.zip ../

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./cf7-propstack-integration.zip
          asset_name: cf7-propstack-integration.zip
          asset_content_type: application/zip
